### ISSUE TITLE
No trained Model

### ISSUE THREAD

**Issue by xxradon** [tensorlayer/openpose-plus#119]
I saw the High-performance Inference using TensorRT part  and I want to do a test on TX2 too,but I can't find the model,will you please share it ?Thanks.

**Comment by lgarithm** [comment]
@xxradon @PrinceP could you try the uploaded demo model?
Thanks.

**Comment by PrinceP** [comment]
Thanks the binding is successful. 
Dealing with Can't open camera issue.
