### ISSUE TITLE
Problem while running live-camera.sh in build_with_cmake

### ISSUE THREAD

**Issue by pragyak412** [tensorlayer/openpose-plus#128]
Building CXX object CMakeFiles/helpers.dir/examples/vis.cpp.o
[ 44%] Building CXX object CMakeFiles/helpers.dir/examples/input.cpp.o
In file included from /home/firelark/group1/openpose-plus/examples/vis.cpp:1:0:
/home/firelark/group1/openpose-plus/examples/vis.h:3:30: fatal error: opencv2/opencv.hpp: No such file or directory
compilation terminated.
make[3]: Leaving directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
CMakeFiles/helpers.dir/build.make:86: recipe for target 'CMakeFiles/helpers.dir/examples/vis.cpp.o' failed
make[3]: *** [CMakeFiles/helpers.dir/examples/vis.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 52%] Built target libstdtracer
make[3]: Entering directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
Scanning dependencies of target tracer
make[3]: Leaving directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
/home/firelark/group1/openpose-plus/examples/input.cpp:4:30: fatal error: opencv2/opencv.hpp: No such file or directory
compilation terminated.
CMakeFiles/helpers.dir/build.make:62: recipe for target 'CMakeFiles/helpers.dir/examples/input.cpp.o' failed
make[3]: *** [CMakeFiles/helpers.dir/examples/input.cpp.o] Error 1
make[3]: Leaving directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
CMakeFiles/Makefile2:334: recipe for target 'CMakeFiles/helpers.dir/all' failed
make[2]: *** [CMakeFiles/helpers.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 55%] Linking CXX static library libtracer.a
make[3]: Leaving directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
[ 55%] Built target tracer
make[2]: Leaving directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
Makefile:160: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/firelark/group1/openpose-plus/cmake-build/Linux'
Makefile:12: recipe for target 'build_with_cmake' failed
make: *** [build_with_cmake] Error 2
****

**Comment by luomai** [comment]
The error message is very clear.... it cannot find opencv2 in your directory. :)
