### ISSUE TITLE
About the uff-runner.py and pretrained npz file

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [tensorlayer/openpose-plus#157]
I used  the two pretrained .npz file from official pretrained-models.The error is :
for 600000.npz
> ValueError: Dimension 0 in both shapes must be equal, but are 7 and 3. Shapes are [7,7,128,128] and [3,3,128,128]. for 'Assign' (op: 'Assign') with input shapes: [7,7,128,128], [3,3,128,128].

for 345000.npz
> ValueError: Dimension 2 in both shapes must be equal, but are 512 and 384. Shapes are [3,3,512,512] and [3,3,384,384]. for 'Assign_2' (op: 'Assign') with input shapes: [3,3,512,512], [3,3,384,384].

When I directly using the pretrained uff file, I got this:

> [TensorRT] ERROR: Tensor imagecannot be both input and output
[TensorRT] INFO: UFFParser: parsing MarkOutput_1
[TensorRT] INFO: UFFParser: parsing MarkOutput_2

How could I use the pretrained npz and uff file?
@fivestarsky

**Comment by vinitmuchhala** [comment]
Hey @MoonBunnyZZZ , I am getting the same error, did you figure out what was causing this issue?
Thanks
