### ISSUE TITLE
Train with Own custom dataset 

### ISSUE THREAD

**Issue by intvo** [tensorlayer/openpose-plus#166]
Thank you for your hard work: I have the following dataset structure that I would like to train: 

Data folder: 
Images: 
 --Image1.jpg 
 --image1.xml 
 --Image2.jpg
 --Image2.xml
 -------------
Should I convert my dataset to coco format ( 1. Object Detection, 2. Keypoint Detection 3.Image Captioning) and then train? if yes, is there any script that helps to convert my dataset to three formats?

Thank you for your help

**Comment by zsdonghao** [comment]
I suggest you follow the coco data format.

1. change `config.DATA.train_data` in `train_config.py` to either `custom` or `coco_and_custom`.
2. put your data into `data/your_data` folder.

**Comment by intvo** [comment]
Thank you for your replay, my dataset format is different than the coco format,so i need a script to convert my dataset to coco format, do you have any suggestion

**Comment by zsdonghao** [comment]
em, you may need to do it yourself

**Comment by intvo** [comment]
I can pay you for this task, please

**Comment by salvador-blanco** [comment]
@intvo did you find a way to do it?
