### ISSUE TITLE
Feature Request: COCO mAP with OKS

### ISSUE THREAD

**Issue by bela127** [tensorlayer/openpose-plus#184]
related to: #183 

To check the performance of a trained model in the OpenPose paper the COCO mAP with Object Keypoint Similarity OKS is used.

I need COCO mAP, so i try working on it.
Help is always appreciated

If everything is Implemented i will file a pull request.

**Comment by abaybektursun** [comment]
Currently under development I believe #129

**Comment by bela127** [comment]
Thanks, can I help with anything?

**Comment by abaybektursun** [comment]
Currently the fork is not passing tests, I guess you can try to figure out why?

**Comment by bela127** [comment]
> Currently the fork is not passing tests, I guess you can try to figure out why?
seems everything is passing, only the WIP status is problematic?
and "At least 1 approving review is required by reviewers with write access"
so i cant help here, but at least i did merge it into my forke.

still doing some tests... but looking good
if I'm finished testing i will leave a last comment here...

**Comment by bela127** [comment]
all tested and fixed/edited some things, on my system it is working now...
as there is already a pull request in process #129 i wont request another one...
if code is wanted: https://github.com/bela127/openpose-plus
