### ISSUE TITLE
Inference scripts not working

### ISSUE THREAD

**Issue by atyshka** [tensorlayer/openpose-plus#191]
I have tried using both the camera and batch image inference scripts but both get stuck at "Leaving cmake directory" and nothing happens. No output in the terminal to indicate an error has occurred. Any ideas what could be causing this? I am running with CUDA 10, TensorRT 5 on a jetson nano.

**Comment by akhalili** [comment]
I am able to run the script. It shows the video stream but nothing is detected.

**Comment by atyshka** [comment]
It appears jetson nano just ran out of memory and froze, closing this
