### ISSUE TITLE
Error build on windows 10

### ISSUE THREAD

**Issue by EnricoBeltramo** [tensorlayer/openpose-plus#233]
I followed step suggested, but I have issue to build on windows.
I tried any different compiler (VS19, VS17, VS15), on x84 on x64.
There are some suggestion how to fix that?

**Comment by antithing** [comment]
Hi, I am having the same problems. It looks like the issue is with the third party stdtensor project, which will not build on Windows.

I am trying to get it working but so far no luck.

**Comment by lgarithm** [comment]
@antithing what is the error you see that makes you believe it was caused by the stdtensor project?

**Comment by lgarithm** [comment]
@antithing I see your issue on the stdml/stdtensor project.

**Comment by antithing** [comment]
These are the steps i took:

Download TensorRT
Download cuDNN.

clone openpose-plus repo.
Build sln with CMake.
Open in visual studio and build open-pose plus project.

I get the following errors:

```

Severity	Code	Description	Project	File	Line	Suppression State
Error	D8021	invalid numeric argument '/Werror' [D:\Deep\OPP\openpose-plus-master\3rdparty\src\stdtensor-repo-build\stdtensor.vcxproj]	stdtensor-repo	D:\Deep\OPP\openpose-plus-master\built\cl	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'unistd.h': No such file or directory [D:\Deep\OPP\openpose-plus-master\3rdparty\src\stdtracer-repo-build\stdtracer.vcxproj]	stdtracer-repo	d:\deep\opp\openpose-plus-master\3rdparty\src\stdtracer-repo\include\bits\stdtracer_log_ctx.hpp	9	
```

To solve these, I open the `cMakeLists.txt` file in `openpose-plus-master\3rdparty\src\stdtensor-repo` and remove the lines:

```
ADD_DEFINITIONS(-Wall)
ADD_DEFINITIONS(-Werror)
ADD_DEFINITIONS(-Wfatal-errors)
```
Trying a build again gives me:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'cxxabi.h': No such file or directory [D:\Deep\OPP\openpose-plus-master\3rdparty\src\stdtensor-repo-build\stdtensor.vcxproj]	stdtensor-repo	d:\deep\opp\openpose-plus-master\3rdparty\src\stdtensor-repo\include\ttl\bits\std_reflect.hpp	2	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'unistd.h': No such file or directory [D:\Deep\OPP\openpose-plus-master\3rdparty\src\stdtracer-repo-build\stdtracer.vcxproj]	stdtracer-repo	d:\deep\opp\openpose-plus-master\3rdparty\src\stdtracer-repo\include\bits\stdtracer_log_ctx.hpp	9	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'stdtracer_disable': No such file or directory	openpose-plus	d:\deep\opp\openpose-plus-master\src\trace.hpp	9	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ttl/tensor': No such file or directory	openpose-plus	d:\deep\opp\openpose-plus-master\src\paf.cpp	3	


Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ttl/cuda_tensor': No such file or directory	openpose-plus	d:\deep\opp\openpose-plus-master\src\uff_runner.cpp	11	
```

**Comment by antithing** [comment]
conmmenting out the <unistd.h> in

`openpose-plus-master\3rdparty\src\stdtracer-repo-build\stdtracer.vcxproj]	stdtracer-repo	d:\deep\opp\openpose-plus-master\3rdparty\src\stdtracer-repo\include\bits\stdtracer_log_ctx`

removes one error, then you get an error about `isatty`.

change the `isatty` to `_isatty`, and add `#include <io.h>` to fix that one.

to fix the missing <ttl/tensor> include, add the include path:

`\openpose-plus-master\3rdparty\src\stdtensor-repo\include`


That leaves three errors:

#include <cxxabi.h> //can't find this file

and 'illegal indirection' in `std_shape.hpp`, another stdtensor file.

**Comment by antithing** [comment]
A little more googling tells me that we can just comment out //#include <cxxabi.h>

and adjust the function below to:

```
template <typename T>
std::string demangled_type_info_name()
{
    int status = 0;
   // return abi::__cxa_demangle(typeid(T).name(), 0, 0, &status);
    return name;
}
```

ref: https://en-mlog.blogspot.com/2012/01/using-cmdlineh-in-visual-c.html

**Comment by antithing** [comment]
Now we have the `illegal indirection` error, and this new one:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2248	'ttl::internal::raw_tensor_mixin<Encoder,ttl::internal::basic_flat_shape<uint32_t>,D,ttl::internal::owner>::Dim': cannot access private typedef declared in class 'ttl::internal::raw_tensor_mixin<Encoder,ttl::internal::basic_flat_shape<uint32_t>,D,ttl::internal::owner>' [D:\Deep\OPP\openpose-plus-master\3rdparty\src\stdtensor-repo-build\stdtensor.vcxproj]	stdtensor-repo	d:\deep\opp\openpose-plus-master\3rdparty\src\stdtensor-repo\include\ttl\bits\raw_tensor.hpp	16	
```
And i am completely stuck!

**Comment by antithing** [comment]
@lgarithm Thanks! Do you have any thoughts on how i can solve these last two errors?

**Comment by lgarithm** [comment]
@antithing I'm wondering how the `raw_tensor.hpp` header gets included in this project, it's actually not used.

**Comment by antithing** [comment]
Hmm indeed!
```

Find all "raw_tensor.hpp", Find Results 1, "Entire Solution ( Including External Items )", ""
  Matching lines: 0    Matching files: 0    Total files searched: 456
```

weird

**Comment by antithing** [comment]
Its included in `tensor.cpp` in stdtensor, perhaps that is where its getting called?

`#include <ttl/experimental/raw_tensor>`

**Comment by lgarithm** [comment]
I'm adding an option to disable that now.

**Comment by lgarithm** [comment]
@antithing could you try #245. After it works, I will make a new release for stdtensor and use the new tag in #245.

**Comment by antithing** [comment]
@lgarithm Thank you! I still need to add:

```
#ifdef linux
#include <unistd.h>
#endif

```

in `\openpose-plus-lg-fix\3rdparty\src\stdtracer-repo\include\bits\stdtracer_log_ctx.hpp`

The raw_tensor errors are gone, but I still get:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2100	illegal indirection	openpose-plus	d:\deep\opp\openpose-plus-lg-fix\3rdparty\include\ttl\bits\std_shape.hpp	53	
```
from this function:

```
    template <typename... I>
    dim_t offset(I... args) const
    {
        static_assert(sizeof...(I) == r, "invalid number of indexes");

        // TODO: expand the expression
        const std::array<dim_t, r> offs({static_cast<dim_t>(args)...});
        dim_t off = 0;
        for (rank_t i = 0; i < r; ++i) { off = off * dims_[i] + offs[i]; }
        return off;
    }
```

Thanks again!

**Comment by antithing** [comment]
.. additionally, in examples/thread_pool.cpp there is an `and` and `or` that need to be `&&` `||` on windows.

**Comment by lgarithm** [comment]
@antithing thanks for the detailed log.

the unistd.h is in stdtracer, it won't be included if trace is not enabled.

for the offset function 

https://github.com/stdml/stdtensor/blob/00519f4e5b3ae9da4a80f6fadf545906a639748c/include/ttl/bits/std_shape.hpp#L51-L61

I currently can't see anything wrong without debug on windows.
But one hack I quickly came up with is to replace it's template implementation with specialised implementation: 

```c++

    dim_t offset(dim_t i, dim_t j) const
    {
        // only for rank == 2
        return i * dims_[1] + j;
    }

    dim_t offset(dim_t i, dim_t j, dim_t k) const
    {
        // only for rank == 3 (maybe we only need this)
        return (i * dims_[1] + j) * dims_[2] + k;
    }
```
to see if it compiles.

**Comment by lgarithm** [comment]
@ganler do you have access to a windows computer?

**Comment by antithing** [comment]
Yes! That compiles. Thank you! 

I have built the live camera example, and i am having one last issue....

```
D:\Deep\OPP\openpose-plus-lg-fix\built\Release>example-live-camera.exe
ERROR: UffParser: Could not open vgg.uff
ERROR: failed to created engine
```
Where can i find the `vgg.uff` file?

**Comment by lgarithm** [comment]
it's probably this one: https://github.com/tensorlayer/openpose-plus/blob/3c8ed52fd5737fc0bbcfe88937153b04df47b0c4/scripts/live-camera.sh#L10

**Comment by lgarithm** [comment]
need to be used with `--model_file=hao28-600000-256x384.uff`

**Comment by antithing** [comment]
Success! I have the example up and running on windows. Thank you very much for your help.

**Comment by antithing** [comment]
@lgarithm one last thing! the `hao28-600000-256x384.uff` model, was that trained with `VGG19 `?

If I re train with mobilenet will I see a speed increase? 

Thanks again!

**Comment by lgarithm** [comment]
@zsdonghao knows the model better

**Comment by zsdonghao** [comment]
`hao28-600000-256x384.uff` was trained with a tiny version of VGG

**Comment by delebash** [comment]
@antithing 
I have installed all of the requirements on Windows 10.  What steps did you take after that to create
your example-live-camera.exe.  Thanks

**Comment by paleomoon** [comment]
@antithing @lgarithm 
Hi, I have the same error "Error	C2100	illegal indirection" in std_shape.hpp, I followed your discussion above, but I can't replace the offset function because it restored to template again during compilation. 
How can I fix the code? Sorry I'm not familiar with the compilation progress. Thanks!
