### ISSUE TITLE
example_batch_detector core dumped

### ISSUE THREAD

**Issue by deep-practice** [tensorlayer/openpose-plus#242]
ERROR: Tensor imagecannot be both input and output
..........
..............
got 2 incomplete humans
got 1 humans
got 1 humans
BodyPart:0-(204.00, 163.00) score=0.97 BodyPart:1-(203.00, 171.00) score=0.99 BodyPart:2-(195.00, 171.00) score=0.98 BodyPart:3-(191.00, 187.00) score=0.86 BodyPart:4-(194.00, 197.00) score=0.84 BodyPart:5-(211.00, 171.00) score=0.94 BodyPart:6-(213.00, 181.00) score=0.77 BodyPart:7-(213.00, 195.00) score=0.66 BodyPart:8-(197.00, 197.00) score=0.88 BodyPart:9-(198.00, 219.00) score=0.89 BodyPart:10-(197.00, 237.00) score=0.83 BodyPart:11-(206.00, 196.00) score=0.82 BodyPart:12-(204.00, 219.00) score=0.93 BodyPart:13-(203.00, 236.00) score=0.85 BodyPart:14-(203.00, 162.00) score=0.92 BodyPart:15-(205.00, 162.00) score=0.83 BodyPart:16-(199.00, 162.00) score=0.76 BodyPart:17-(211.00, 162.00) score=0.37 score=30.42
// inferenced 3 images of 256 x 384, took 0.21s, mean: 70.66ms, FPS: 14.151508, batch size: 8, use f16: 0, gauss kernel size: 17
terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
Aborted (core dumped)

**Comment by tonye0115** [comment]
My question is the same
-----------------------------------------------------
root@6d219fe96782:~/workspace/openpose-plus/cmake-build/Linux# ./example-batch-detector --use_f16=true
create_pose_detector
ERROR: Tensor image cannot be both input and output
binding 0: name: image type0(3, 256, 384)
binding 1: name: outputs/paf type0(38, 32, 48)
binding 2: name: outputs/conf type0(19, 32, 48)
Arguments parsed, running models...
batch read images
batch run tensorRT
selected 61 peaks with value > 0.050000
got 5 incomplete humans
got 4 humans
got 4 humans
BodyPart:0-(196.00, 114.00) score=0.88 BodyPart:1-(195.00, 116.00) score=0.93 BodyPart:2-(179.00, 118.00) score=0.86 BodyPart:3-(165.00, 134.00) score=0.85 BodyPart:4-(176.00, 140.00) score=0.70 BodyPart:5-(211.00, 115.00) score=0.92 BodyPart:6-(221.00, 124.00) score=0.86 BodyPart:7-(219.00, 138.00) score=0.81 BodyPart:8-(187.00, 155.00) score=0.94 BodyPart:9-(196.00, 181.00) score=0.85 BodyPart:10-(203.00, 211.00) score=0.78 BodyPart:11-(204.00, 154.00) score=0.83 BodyPart:12-(205.00, 180.00) score=0.77 BodyPart:13-(205.00, 211.00) score=0.57 BodyPart:14-(195.00, 109.00) score=0.82 BodyPart:15-(200.00, 109.00) score=0.79 BodyPart:16-(188.00, 108.00) score=0.73 BodyPart:17-(203.00, 108.00) score=0.48 score=28.78
BodyPart:1-(284.00, 145.00) score=0.83 BodyPart:2-(300.00, 144.00) score=0.81 BodyPart:3-(299.00, 156.00) score=0.25 BodyPart:5-(274.00, 146.00) score=0.79 BodyPart:6-(269.00, 157.00) score=0.33 BodyPart:8-(292.00, 179.00) score=0.77 BodyPart:9-(292.00, 204.00) score=0.81 BodyPart:10-(299.00, 235.00) score=0.88 BodyPart:11-(282.00, 179.00) score=0.56 BodyPart:12-(277.00, 211.00) score=0.56 BodyPart:13-(279.00, 237.00) score=0.53 BodyPart:16-(293.00, 130.00) score=0.69 BodyPart:17-(277.00, 130.00) score=0.74 score=17.58
BodyPart:1-(252.00, 163.00) score=0.92 BodyPart:2-(268.00, 164.00) score=0.85 BodyPart:3-(281.00, 184.00) score=0.47 BodyPart:4-(277.00, 194.00) score=0.45 BodyPart:5-(234.00, 160.00) score=0.82 BodyPart:6-(219.00, 177.00) score=0.70 BodyPart:7-(220.00, 181.00) score=0.39 BodyPart:8-(258.00, 204.00) score=0.84 BodyPart:9-(251.00, 242.00) score=0.78 BodyPart:11-(236.00, 203.00) score=0.82 BodyPart:12-(229.00, 235.00) score=0.74 BodyPart:16-(261.00, 148.00) score=0.66 BodyPart:17-(245.00, 148.00) score=0.67 score=18.74
BodyPart:1-(0.00, 173.00) score=0.31 BodyPart:2-(11.00, 178.00) score=0.81 BodyPart:3-(16.00, 199.00) score=0.75 BodyPart:4-(16.00, 218.00) score=0.92 BodyPart:8-(0.00, 213.00) score=0.28 BodyPart:9-(0.00, 243.00) score=0.16 BodyPart:14-(11.00, 156.00) score=0.09 BodyPart:16-(0.00, 160.00) score=0.48 score=7.80
selected 13 peaks with value > 0.050000
got 1 incomplete humans
got 1 humans
got 1 humans
BodyPart:0-(90.00, 80.00) score=0.80 BodyPart:1-(77.00, 122.00) score=0.48 BodyPart:2-(66.00, 117.00) score=0.59 BodyPart:3-(139.00, 167.00) score=0.82 BodyPart:4-(171.00, 124.00) score=0.86 BodyPart:5-(91.00, 124.00) score=0.29 BodyPart:6-(123.00, 211.00) score=0.38 BodyPart:7-(189.00, 202.00) score=0.66 BodyPart:8-(59.00, 221.00) score=0.06 BodyPart:14-(81.00, 73.00) score=0.81 BodyPart:15-(99.00, 73.00) score=0.92 BodyPart:16-(66.00, 79.00) score=0.82 BodyPart:17-(108.00, 78.00) score=0.75 score=16.43
// inferenced 2 images of 256 x 384, took 0.41s, mean: 207.35ms, FPS: 4.822662, batch size: 2, use f16: 1, gauss kernel size: 17
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFree failed
Aborted (core dumped)

**Comment by ganler** [comment]
@deep-practice @tonye0115 Sorry about this. This bug is fixed but not pushed to the current master branch. Before that, you can fix this by using this [`post_process.cpp`](https://github.com/tensorlayer/openpose-plus/blob/refactorization/src/post_process.hpp).  I'll push this change to the master soon.

BTW, the errors only occur when the program exists. And it was discussed [here](https://github.com/tensorlayer/openpose-plus/pull/238).

**Comment by ganler** [comment]
Solved in the lastest master branch.
