### ISSUE TITLE
openpose-plus/tree/refactorization   make pack_trace  error

### ISSUE THREAD

**Issue by tonye0115** [tensorlayer/openpose-plus#244]
I pulled the branch code "https://github.com/tensorlayer/openpose-plus/tree/refactorization" to use the tensorrt acceleration, but an error when  make compiling

I configured cuda and tensorrt strictly according to the documentation:

Make sure that the header files & libraries of TensorRT & CUDA are in the /usr/local/cuda/targets/${ARCH}-linux's include & lib folder.
Or you may need to set CUDA_RT as /path/to/TensorRT when executing cmake commands.

-----------------------------------------------------
cd /root/workspace/openpose-plus
export CUDA_RT=/opt/TensorRT-6.0.1.8
make pack_trace -j 128
---------------------------------------------------------------------
[ 80%] Built target example-batch-detector
[ 84%] Built target example-stream-detector
/root/workspace/openpose-plus/src/tensorrt.cpp: In function 'size_t swiftpose::dnn::sizeof_element(nvinfer1::DataType)':
/root/workspace/openpose-plus/src/tensorrt.cpp:44:30: error: 'kBOOL' is not a member of 'nvinfer1::DataType'
     case nvinfer1::DataType::kBOOL:  // TODO. Validation.
                              ^~~~~
/root/workspace/openpose-plus/src/tensorrt.cpp: In function 'std::__cxx11::string swiftpose::dnn::to_string(nvinfer1::DataType)':
/root/workspace/openpose-plus/src/tensorrt.cpp:80:30: error: 'kBOOL' is not a member of 'nvinfer1::DataType'
     case nvinfer1::DataType::kBOOL:  // TODO. Validation.
                              ^~~~~
/root/workspace/openpose-plus/src/tensorrt.cpp: In function 'nvinfer1::ICudaEngine* swiftpose::dnn::loadModelAndCreateEngine(const char*, int, nvuffparser::IUffParser*, nvinfer1::DataType)':
/root/workspace/openpose-plus/src/tensorrt.cpp:95:78: warning: 'virtual nvinfer1::INetworkDefinition* nvinfer1::IBuilder::createNetwork()' is deprecated [-Wdeprecated-declarations]
     destroy_ptr<nvinfer1::INetworkDefinition> network(builder->createNetwork());
                                                                              ^
In file included from /root/workspace/openpose-plus/src/tensorrt.cpp:4:0:
/usr/local/cuda/include/NvInfer.h:5431:58: note: declared here
     TRT_DEPRECATED virtual nvinfer1::INetworkDefinition* createNetwork() TRTNOEXCEPT = 0;
                                                          ^~~~~~~~~~~~~
/root/workspace/openpose-plus/src/tensorrt.cpp:105:45: warning: 'virtual nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildCudaEngine(nvinfer1::INetworkDefinition&)' is deprecated [-Wdeprecated-declarations]
     return builder->buildCudaEngine(*network);
                                             ^
In file included from /root/workspace/openpose-plus/src/tensorrt.cpp:4:0:
/usr/local/cuda/include/NvInfer.h:5566:51: note: declared here
     TRT_DEPRECATED virtual nvinfer1::ICudaEngine* buildCudaEngine(
                                                   ^~~~~~~~~~~~~~~
/root/workspace/openpose-plus/src/tensorrt.cpp: In function 'nvinfer1::ICudaEngine* swiftpose::dnn::create_engine(const string&, cv::Size, const string&, const std::vector<std::__cxx11::basic_string<char> >&, int, nvinfer1::DataType)':
/root/workspace/openpose-plus/src/tensorrt.cpp:120:65: warning: 'DimsCHW' is deprecated [-Wdeprecated-declarations]
         nvinfer1::DimsCHW(3, input_size.height, input_size.width),
                                                                 ^
In file included from /root/workspace/openpose-plus/src/tensorrt.cpp:4:0:
/usr/local/cuda/include/NvInfer.h:206:22: note: declared here
 class TRT_DEPRECATED DimsCHW : public Dims3
                      ^~~~~~~
CMakeFiles/swiftpose.dir/build.make:105: recipe for target 'CMakeFiles/swiftpose.dir/src/tensorrt.cpp.o' failed
make[3]: *** [CMakeFiles/swiftpose.dir/src/tensorrt.cpp.o] Error 1
make[3]: Leaving directory '/root/workspace/openpose-plus/cmake-build'
CMakeFiles/Makefile2:370: recipe for target 'CMakeFiles/swiftpose.dir/all' failed
make[2]: *** [CMakeFiles/swiftpose.dir/all] Error 2
make[2]: Leaving directory '/root/workspace/openpose-plus/cmake-build'
Makefile:179: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/workspace/openpose-plus/cmake-build'
Makefile:22: recipe for target 'pack_trace' failed
make: *** [pack_trace] Error 2

**Comment by ganler** [comment]
Hi, the `refactorization` branch is still under development. Please use the codes in the master branch(which already solved the core dump issue I think):-)

**Comment by ganler** [comment]
But I think the `refactorization` branch can be compiled. Could you please delete files in the cmake-build directory and recompile?

**Comment by tonye0115** [comment]
I changed tensorrt7 and it will compile

However, I ran example-batch-detector and suspected that uff to tensorrt did not succeed, and the final running result showed that it could only reach 22fps (my GPU card is v100), which is far from the 50fps in the document. Could you please check if I made a mistake?


The master branch of code reported the same error, which we think is that it did not use tensorrt to accelerate the success.
-----------------------------------------------------------------------------

ERROR: Tensor image cannot be both input and output
ERROR: Tensor image cannot be both input and output
ERROR: Tensor image cannot be both input and output

------------------------------------------------------------------------------------------
root@0e4946c857b5:~/workspace/openpose-plus/cmake-build# export CUDA_VISIBLE_DEVICES=0
root@0e4946c857b5:~/workspace/openpose-plus/cmake-build# cd /root/workspace/openpose-plus/cmake-build/
root@0e4946c857b5:~/workspace/openpose-plus/cmake-build# ./example-batch-detector --use_f16=true
{ // [main]
Add file: ../data/media/COCO_val2014_000000000241.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000488.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000257.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000544.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000192.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000459.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000428.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000360.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000474.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000415.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000536.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000338.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000294.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000328.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000395.jpg into batch.
Add file: ../data/media/COCO_val2014_000000000357.jpg into batch.
    { // [create_engine]
ERROR: Tensor image cannot be both input and output
ERROR: Tensor image cannot be both input and output
ERROR: Tensor image cannot be both input and output
....................................................................
5.00, 132.00) score=0.15 BodyPart:16-(221.00, 131.00) score=0.92 score=18.87
                } // [draw_results] took 9.22ms
            } // [draw_results] took 17.41ms
        } // [batch run process PAF and draw results] took 91.77ms
    } // [one_batch] took 341.10ms
// inferenced 16 images of 256 x 384, took 0.70s, mean: 43.83ms, FPS: 22.814950, batch size: 8, use f16: 1, gauss kernel size: 17
} // [main] took 140.16s
// profile info logged to file://trace.log
        summary of tracer_ctx_t::global (140.158724s)

**Comment by ganler** [comment]
The speed of cold starting the `example-batch-detector` is usually slow(usually ~20FPS on my 1070Ti). This is because of the cold start and the small data amount(20 images) in the `example-batch-detector`. I suggest you to run it more than twice of just glob more images. :-)

**Comment by ganler** [comment]
Closed. Feel free to reopen this if you have further questions.
