### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by MoustafaAyoub** [tensorlayer/openpose-plus#55]
I would like to retrain the model on different data with less points (head, upper body, lower body, leg) and on different kinds of pictures. I want to make it as fast as possible (planning to use the mobile net).
I was planning to drop the last layer of the model and create a new one with 4 outputs, and then retrain this layer and freeze the training on the others.

However, I have no idea how should I use MY labeled data and train on them.
Can someone help?

PS: Will this program support real time detection anytime soon?

**Comment by zsdonghao** [comment]
@MoustafaAyoub Hi, I asked you in Slack, here is the copy:

First of all, using less key points would not speed up the model.

If you like to, you need to do the following 2 things:

1. change `n_pos` in config file, and the `keypoint_xxx` which require `anno_list`.
2. format the COCO dataset to your format.
3. put your dataset into `data/your_data`, change `config.DATA.train_data` to `coco_and_yours`.

Hope it help.

**Comment by zsdonghao** [comment]
hi, hope it can solve your problem, feel free to reopen if you have any other problems.
